# This is a basic workflow to help you get started with Actions

name: vegans develop workflow

on:
  pull_request:
    branches:
      - develop
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
        os: [macos-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "1. Clone repository"
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: "2. Set up Python ${{ matrix.python }}"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      # Install requirements
      - name: Install Tox and any other packages
        run: pip install -r requirements/all.txt

      # Run tox.ini which runs pytest
      - name: Run Tox
        run: tox -e py



